#ifndef UTILS_ENEMYTYPESANDSTATES_HH_
#define UTILS_ENEMYTYPESANDSTATES_HH_

enum EnemyType {
	ENEMY_TYPE_RUNNER,
	ENEMY_TYPE_RIFLEMAN,

	// Do not add enemy types beyond this point
	ENEMY_TYPE_COUNT
};

const int MAX_ENEMY_TYPES = ENEMY_TYPE_COUNT;

enum EnemyRunnerStates {
	RUNNER_STATE_RUNNING_LEFT,
	RUNNER_STATE_RUNNING_RIGHT,

	// Do not add states beyond this point
	RUNNER_STATES_COUNT
};

const int MAX_RUNNER_STATES = RUNNER_STATES_COUNT;

enum EnemyRiflemanStates {
	RIFLEMAN_STATE_LEFT_UP,
	RIFLEMAN_STATE_LEFT_FRONT,
	RIFLEMAN_STATE_LEFT_DOWN,
	RIFLEMAN_STATE_RIGHT_UP,
	RIFLEMAN_STATE_RIGHT_FRONT,
	RIFLEMAN_STATE_RIGHT_DOWN,

	// Do not add states beyond this point
	RIFLEMAN_STATES_COUNT
};

const int MAX_RIFLEMAN_STATES = RIFLEMAN_STATES_COUNT;

#endif /* UTILS_ENEMYTYPESANDSTATES_HH_ */
