#ifndef UTILS_ITEMTYPES_HH_
#define UTILS_ITEMTYPES_HH_

#define MAX_ITEMS_TYPES 7

#define ITEMS_WIDTH 40
#define ITEMS_HEIGHT 25

enum ItemType {
		TYPE_FIREBALLFALCON,
		TYPE_FORCEFIELDFALCON,
		TYPE_LASERFALCON,
		TYPE_MACHINEGUNFALCON,
		TYPE_RAPIDFIREFALCON,
		TYPE_SPREADGUNFALCON,
		TYPE_ERROR
};

#endif /* UTILS_ITEMTYPES_HH_ */
