#define MAX_ITEMS_TYPES 7

#define ITEMS_WIDTH 40
#define ITEMS_HEIGHT 25

enum ItemType {
		TYPE_FIREBALLFALCON,
		TYPE_FIREFIELDFALCON,
		TYPE_LASERFALCON,
		TYPE_MACHINEGUNFALCON,
		TYPE_RAPIDFIREFALCON,
		TYPE_SPREADGUNFALCON,
		TYPE_ERROR
};
